let languages = {
  en: {
    home: {
      pageTitle: "Community | Lobby",
      sideNavTitle: "Communities",
      sideNavMenu: {
        create: "Create Community",
        settings: "Settings",
      },
      searchPlaceholder: "Search communities",
      openDiscoverText: "Open Discover",
      createCommunityText: "Create one",
      addRoomBtn: "Add Room",
      joinCommunityText: "You haven't join this community",
      openDiscoverToJoin: "Open Discover to join",
      loadingCommunities: "Loading communities",
      loadingRooms: "Loading rooms",
      lobbyText: "Send and receive messages without keeping your phone online.",
    },
    discover: {
      pageTitle: "Discover | Lobby",
      sideNavTitle: "Discover",
      sideNavMenu: {
        settings: "Settings",
      },
      searchPlaceholder: "Search communities",
      open: "Open",
      communityText: "Community",
      joinedCommunity: "Joined community",
      createCommunityText: "Create one",
      openBtn: "Open",
      joinBtn: "Join",
      leaveBtn: "Leave",
      reportBtn: "Leave",
      loadingCommunities: "Loading communities",
      member: "member",
      members: "members",
      lobbyText: "Send and receive messages without keeping your phone online.",
    },
    settings: {
      pageTitle: "Settings | Lobby",
      sideNavTitle: "Settings",
      searchPlaceholder: "Search settings",
      createCommunityText: "Create one",
      loadingSettings: "Loading settings",
      general: "General",
      profile: "Profile",
      chats: "Chats",
      notification: "Notification",
      personalization: "Personalization",
      help: "Help",
      inviteFriends: "Invite friends",
    },
    settingsGeneral: {
      pageTitle: "General | Settings",
      title: "General",
      languageText: "Language",
    },
    settingsHelp: {
      pageTitle: "Help | Settings",
      title: "Help",
      helpCenterText: "Help center",
      helpCenterSubText: "Get help, contact us",
      termAndPrivacyText: "Terms and Privacy Policy",
      aboutLobbyText: "About Lobby",
    },
    settingsInvite: {
      title: "Invite friends",
      inviteFriendsText: "Invite friends",
      inviteFriendsSubText:
        "Invite your friend to lobby, connect with your friends",
      copyLinkBtn: "Copy Invitation link",
      copyLinkAlert: "&#x1F4CB Link copied to clipboard",
    },
    settingsPersonalization: {
      pageTitle: "Personalize | Settings",
      title: "Personalize",
      chooseThemeText: "Choose your theme",
      chooseThemeSubText: "Change the theme of your Lobby App",
      themeSystem: "System",
      themeLight: "Light",
      themeDark: "Dark",
    },
    settingsProfile: {
      pageTitle: "Profile | Settings",
      title: "Profile",
      editedProfileText: "Edit profile",
      signOutText: "Sign out",
      bioText: "Bio",
      noBioText: "You haven't add your bio yet.",
      dobText: "Date of birth",
      dobSubText: "Your date of birth isn't visible to other users",
      noDobText: "You haven't add your date of birth yet.",
    },
    sideNavMobileNavMenu: {
      communitiesText: "Communities",
      discoverText: "Discover",
      settingsText: "Settings",
      profileText: "Profile",
    },
    createCommunityModal: {
      title: "Create Community",
      namePlaceholder: "Name",
      descriptionPlaceholder: "Description",
      createCommunityBtn: "Create Community",
      closeBtn: "Close",
    },
    createRoomModal: {
      title: "Create Room",
      namePlaceholder: "Name",
      descriptionPlaceholder: "Description",
      enableMessage: "Allow community members to send message",
      createRoomBtn: "Create Room",
      closeBtn: "Close",
    },
    chats: {
      sendingText: "Sending....",
      todayText: "Today",
      yesterdayText: "Yesterday",
      communityInfoText: "Community info",
      loadingChat: "Loading chat",
      joinCommunityText: "You haven't join this community",
      joinCommunityBtnText: "Join to see messages",
      chatInputPlaceHolder: "Type your message",
      disabledInputPlaceHolder: "Only admin can send message",
    },
    notFound: {
      pageTitle: "404 Page no found",
      title: "404 Page no found",
    },
  },
  fr: {
    home: {
      pageTitle: "Communauté | Lobby",
      sideNavTitle: "Communautés",
      sideNavMenu: {
        create: "Créer une communauté",
        settings: "Paramètres",
      },
      searchPlaceholder: "Rechercher des communautés",
      openDiscoverText: "Ouvrir Découverte",
      createCommunityText: "Créer une",
      addRoomBtn: "Ajouter une salle",
      joinCommunityText: "Vous n'avez pas rejoint cette communauté",
      openDiscoverToJoin: "Ouvrir Découverte pour rejoindre",
      loadingCommunities: "Chargement des communautés",
      loadingRooms: "Chargement des salles",
      lobbyText:
        "Envoyez et recevez des messages sans garder votre téléphone en ligne.",
    },
    discover: {
      pageTitle: "Découverte | Lobby",
      sideNavTitle: "Découverte",
      sideNavMenu: {
        settings: "Paramètres",
      },
      searchPlaceholder: "Rechercher des communautés",
      open: "Ouvrir",
      communityText: "Communauté",
      joinedCommunity: "Communauté rejointe",
      createCommunityText: "Créer une",
      openBtn: "Rejoindre",
      joinBtn: "Rejoindre",
      leaveBtn: "Quitter",
      reportBtn: "Signaler",
      loadingCommunities: "Chargement des communautés",
      member: "membre",
      members: "membres",
      lobbyText:
        "Envoyez et recevez des messages sans garder votre téléphone en ligne.",
    },
    settings: {
      pageTitle: "Paramètres | Lobby",
      sideNavTitle: "Paramètres",
      searchPlaceholder: "Rechercher des paramètres",
      createCommunityText: "Créer une",
      loadingSettings: "Chargement des paramètres",
      general: "Général",
      profile: "Profil",
      chats: "Discussions",
      notification: "Notification",
      personalization: "Personnalisation",
      help: "Aide",
      inviteFriends: "Inviter des amis",
    },
    settingsGeneral: {
      pageTitle: "Général | Paramètres",
      title: "Général",
      languageText: "Langue",
    },
    settingsHelp: {
      pageTitle: "Aide | Paramètres",
      title: "Aide",
      helpCenterText: "Centre d'aide",
      helpCenterSubText: "Obtenez de l'aide, contactez-nous",
      termAndPrivacyText: "Conditions et politique de confidentialité",
      aboutLobbyText: "À propos de Lobby",
    },
    settingsInvite: {
      title: "Inviter des amis",
      inviteFriendsText: "Inviter des amis",
      inviteFriendsSubText: "Invitez vos amis à Lobby, connectez-vous avec eux",
      copyLinkBtn: "Copier le lien d'invitation",
      copyLinkAlert: "&#x1F4CB Lien copié dans le presse-papiers",
    },
    settingsPersonalization: {
      pageTitle: "Personnaliser | Paramètres",
      title: "Personnaliser",
      chooseThemeText: "Choisissez votre thème",
      chooseThemeSubText: "Changez le thème de votre application Lobby",
      themeSystem: "Système",
      themeLight: "Clair",
      themeDark: "Sombre",
    },
    settingsProfile: {
      pageTitle: "Profil | Paramètres",
      title: "Profil",
      editedProfileText: "Modifier le profil",
      signOutText: "Déconnexion",
      bioText: "Biographie",
      noBioText: "Vous n'avez pas encore ajouté votre biographie.",
      dobText: "Date de naissance",
      dobSubText:
        "Votre date de naissance n'est pas visible par les autres utilisateurs",
      noDobText: "Vous n'avez pas encore ajouté votre date de naissance.",
    },
    sideNavMobileNavMenu: {
      communitiesText: "Communautés",
      discoverText: "Découverte",
      settingsText: "Paramètres",
      profileText: "Profil",
    },
    createCommunityModal: {
      title: "Créer une communauté",
      namePlaceholder: "Nom",
      descriptionPlaceholder: "Description",
      createCommunityBtn: "Créer une communauté",
      closeBtn: "Fermer",
    },
    createRoomModal: {
      title: "Créer une salle",
      namePlaceholder: "Nom",
      descriptionPlaceholder: "Description",
      enableMessage:
        "Autoriser les membres de la communauté à envoyer des messages",
      createRoomBtn: "Créer une salle",
      closeBtn: "Fermer",
    },
    chats: {
      sendingText: "Envoi....",
      todayText: "Aujourd'hui",
      yesterdayText: "Hier",
      communityInfoText: "Informations sur la communauté",
      loadingChat: "Chargement de la discussion",
      joinCommunityText: "Vous n'avez pas rejoint cette communauté",
      joinCommunityBtnText: "Rejoindre pour voir les messages",
      chatInputPlaceHolder: "Tapez votre message",
      disabledInputPlaceHolder:
        "Seul l'administrateur peut envoyer des messages",
    },
    notFound: {
      pageTitle: "404 Page non trouvée",
      title: "404 Page non trouvée",
    },
  },
  es: {
    home: {
      pageTitle: "Comunidad | Lobby",
      sideNavTitle: "Comunidades",
      sideNavMenu: {
        create: "Crear Comunidad",
        settings: "Configuración",
      },
      searchPlaceholder: "Buscar comunidades",
      openDiscoverText: "Abrir Descubrir",
      createCommunityText: "Crear una",
      addRoomBtn: "Agregar Sala",
      joinCommunityText: "No te has unido a esta comunidad",
      openDiscoverToJoin: "Abrir Descubrir para unirse",
      loadingCommunities: "Cargando comunidades",
      loadingRooms: "Cargando salas",
      lobbyText: "Envía y recibe mensajes sin mantener tu teléfono en línea.",
    },
    discover: {
      pageTitle: "Descubrir | Lobby",
      sideNavTitle: "Descubrir",
      sideNavMenu: {
        settings: "Configuración",
      },
      searchPlaceholder: "Buscar comunidades",
      open: "Abrir",
      communityText: "Comunidad",
      joinedCommunity: "Comunidad unida",
      createCommunityText: "Crear una",
      openBtn: "Unirse",
      joinBtn: "Unirse",
      leaveBtn: "Dejar",
      reportBtn: "Reportar",
      loadingCommunities: "Cargando comunidades",
      member: "miembro",
      members: "miembros",
      lobbyText: "Envía y recibe mensajes sin mantener tu teléfono en línea.",
    },
    settings: {
      pageTitle: "Configuración | Lobby",
      sideNavTitle: "Configuración",
      searchPlaceholder: "Buscar configuración",
      createCommunityText: "Crear una",
      loadingSettings: "Cargando configuración",
      general: "General",
      profile: "Perfil",
      chats: "Chats",
      notification: "Notificación",
      personalization: "Personalización",
      help: "Ayuda",
      inviteFriends: "Invitar amigos",
    },
    settingsGeneral: {
      pageTitle: "General | Configuración",
      title: "General",
      languageText: "Idioma",
    },
    settingsHelp: {
      pageTitle: "Ayuda | Configuración",
      title: "Ayuda",
      helpCenterText: "Centro de Ayuda",
      helpCenterSubText: "Obtén ayuda, contáctanos",
      termAndPrivacyText: "Términos y Política de Privacidad",
      aboutLobbyText: "Acerca de Lobby",
    },
    settingsInvite: {
      title: "Invitar amigos",
      inviteFriendsText: "Invitar amigos",
      inviteFriendsSubText: "Invita a tus amigos a Lobby, conéctate con ellos",
      copyLinkBtn: "Copiar enlace de invitación",
      copyLinkAlert: "&#x1F4CB Enlace copiado al portapapeles",
    },
    settingsPersonalization: {
      pageTitle: "Personalizar | Configuración",
      title: "Personalizar",
      chooseThemeText: "Elige tu tema",
      chooseThemeSubText: "Cambia el tema de tu aplicación Lobby",
      themeSystem: "Sistema",
      themeLight: "Claro",
      themeDark: "Oscuro",
    },
    settingsProfile: {
      pageTitle: "Perfil | Configuración",
      title: "Perfil",
      editedProfileText: "Editar perfil",
      signOutText: "Cerrar sesión",
      bioText: "Biografía",
      noBioText: "Aún no has agregado tu biografía.",
      dobText: "Fecha de nacimiento",
      dobSubText: "Tu fecha de nacimiento no es visible para otros usuarios",
      noDobText: "Aún no has agregado tu fecha de nacimiento.",
    },
    sideNavMobileNavMenu: {
      communitiesText: "Comunidades",
      discoverText: "Descubrir",
      settingsText: "Configuración",
      profileText: "Perfil",
    },
    createCommunityModal: {
      title: "Crear Comunidad",
      namePlaceholder: "Nombre",
      descriptionPlaceholder: "Descripción",
      createCommunityBtn: "Crear Comunidad",
      closeBtn: "Cerrar",
    },
    createRoomModal: {
      title: "Crear Sala",
      namePlaceholder: "Nombre",
      descriptionPlaceholder: "Descripción",
      enableMessage: "Permitir a los miembros de la comunidad enviar mensajes",
      createRoomBtn: "Crear Sala",
      closeBtn: "Cerrar",
    },
    chats: {
      sendingText: "Enviando....",
      todayText: "Hoy",
      yesterdayText: "Ayer",
      communityInfoText: "Información de la comunidad",
      loadingChat: "Cargando chat",
      joinCommunityText: "No te has unido a esta comunidad",
      joinCommunityBtnText: "Unirse para ver mensajes",
      chatInputPlaceHolder: "Escribe tu mensaje",
      disabledInputPlaceHolder: "Solo el administrador puede enviar mensajes",
    },
    notFound: {
      pageTitle: "404 Página no encontrada",
      title: "404 Página no encontrada",
    },
  },
  ar: {
    home: {
      pageTitle: "مجتمع | Lobby",
      sideNavTitle: "المجتمعات",
      sideNavMenu: {
        create: "إنشاء مجتمع",
        settings: "الإعدادات",
      },
      searchPlaceholder: "البحث عن المجتمعات",
      openDiscoverText: "فتح اكتشاف",
      createCommunityText: "إنشاء واحد",
      addRoomBtn: "إضافة غرفة",
      joinCommunityText: "أنت لم تنضم إلى هذا المجتمع",
      openDiscoverToJoin: "افتح اكتشاف للانضمام",
      loadingCommunities: "تحميل المجتمعات",
      loadingRooms: "تحميل الغرف",
      lobbyText:
        "أرسل واستقبل الرسائل دون الحاجة إلى إبقاء هاتفك متصلاً بالإنترنت.",
    },
    discover: {
      pageTitle: "اكتشاف | Lobby",
      sideNavTitle: "اكتشاف",
      sideNavMenu: {
        settings: "الإعدادات",
      },
      searchPlaceholder: "البحث عن المجتمعات",
      open: "فتح",
      communityText: "مجتمع",
      joinedCommunity: "مجتمع منضم",
      createCommunityText: "إنشاء واحد",
      openBtn: "انضمام",
      joinBtn: "انضمام",
      leaveBtn: "مغادرة",
      reportBtn: "إبلاغ",
      loadingCommunities: "تحميل المجتمعات",
      member: "عضو",
      members: "أعضاء",
      lobbyText:
        "أرسل واستقبل الرسائل دون الحاجة إلى إبقاء هاتفك متصلاً بالإنترنت.",
    },
    settings: {
      pageTitle: "الإعدادات | Lobby",
      sideNavTitle: "الإعدادات",
      searchPlaceholder: "البحث في الإعدادات",
      createCommunityText: "إنشاء واحد",
      loadingSettings: "تحميل الإعدادات",
      general: "عام",
      profile: "الملف الشخصي",
      chats: "الدردشات",
      notification: "الإشعارات",
      personalization: "التخصيص",
      help: "المساعدة",
      inviteFriends: "دعوة الأصدقاء",
    },
    settingsGeneral: {
      pageTitle: "عام | الإعدادات",
      title: "عام",
      languageText: "اللغة",
    },
    settingsHelp: {
      pageTitle: "المساعدة | الإعدادات",
      title: "المساعدة",
      helpCenterText: "مركز المساعدة",
      helpCenterSubText: "احصل على المساعدة، اتصل بنا",
      termAndPrivacyText: "الشروط وسياسة الخصوصية",
      aboutLobbyText: "حول Lobby",
    },
    settingsInvite: {
      title: "دعوة الأصدقاء",
      inviteFriendsText: "دعوة الأصدقاء",
      inviteFriendsSubText: "ادعُ أصدقاءك إلى Lobby وتواصل معهم",
      copyLinkBtn: "نسخ رابط الدعوة",
      copyLinkAlert: "&#x1F4CB تم نسخ الرابط إلى الحافظة",
    },
    settingsPersonalization: {
      pageTitle: "تخصيص | الإعدادات",
      title: "تخصيص",
      chooseThemeText: "اختر السمة",
      chooseThemeSubText: "غيّر سمة تطبيق Lobby",
      themeSystem: "النظام",
      themeLight: "فاتح",
      themeDark: "داكن",
    },
    settingsProfile: {
      pageTitle: "الملف الشخصي | الإعدادات",
      title: "الملف الشخصي",
      editedProfileText: "تعديل الملف الشخصي",
      signOutText: "تسجيل الخروج",
      bioText: "السيرة الذاتية",
      noBioText: "لم تقم بإضافة سيرتك الذاتية بعد.",
      dobText: "تاريخ الميلاد",
      dobSubText: "تاريخ ميلادك غير مرئي للمستخدمين الآخرين",
      noDobText: "لم تقم بإضافة تاريخ ميلادك بعد.",
    },
    sideNavMobileNavMenu: {
      communitiesText: "المجتمعات",
      discoverText: "اكتشاف",
      settingsText: "الإعدادات",
      profileText: "الملف الشخصي",
    },
    createCommunityModal: {
      title: "إنشاء مجتمع",
      namePlaceholder: "الاسم",
      descriptionPlaceholder: "الوصف",
      createCommunityBtn: "إنشاء مجتمع",
      closeBtn: "إغلاق",
    },
    createRoomModal: {
      title: "إنشاء غرفة",
      namePlaceholder: "الاسم",
      descriptionPlaceholder: "الوصف",
      enableMessage: "السماح لأعضاء المجتمع بإرسال الرسائل",
      createRoomBtn: "إنشاء غرفة",
      closeBtn: "إغلاق",
    },
    chats: {
      sendingText: "جارٍ الإرسال....",
      todayText: "اليوم",
      yesterdayText: "أمس",
      communityInfoText: "معلومات المجتمع",
      loadingChat: "تحميل الدردشة",
      joinCommunityText: "أنت لم تنضم إلى هذا المجتمع",
      joinCommunityBtnText: "انضم لرؤية الرسائل",
      chatInputPlaceHolder: "اكتب رسالتك",
      disabledInputPlaceHolder: "فقط المسؤول يمكنه إرسال الرسائل",
    },
    notFound: {
      pageTitle: "404 الصفحة غير موجودة",
      title: "404 الصفحة غير موجودة",
    },
  },
  yo: {
    home: {
      pageTitle: "Awujọ | Lobby",
      sideNavTitle: "Awujọ",
      sideNavMenu: {
        create: "Ṣẹda Awujọ",
        settings: "Eto",
      },
      searchPlaceholder: "Wa fun Awujọ",
      openDiscoverText: "Ṣii Awari",
      createCommunityText: "Ṣẹda ọkan",
      addRoomBtn: "Fi yara kun",
      joinCommunityText: "O ko ti darapọ mọ awujọ yii",
      openDiscoverToJoin: "Ṣii Awari lati darapọ",
      loadingCommunities: "N fifuye awujọ",
      loadingRooms: "N fifuye yara",
      lobbyText:
        "Firanṣẹ ati gba awọn ifiranṣẹ laisi sisopọ foonu rẹ sori ayelujara.",
    },
    discover: {
      pageTitle: "Awari | Lobby",
      sideNavTitle: "Awari",
      sideNavMenu: {
        settings: "Eto",
      },
      searchPlaceholder: "Wa fun Awujọ",
      open: "Ṣii",
      communityText: "Awujọ",
      joinedCommunity: "Darapọ mọ awujọ",
      createCommunityText: "Ṣẹda ọkan",
      openBtn: "Darapọ",
      joinBtn: "Darapọ",
      leaveBtn: "Fi silẹ",
      reportBtn: "Fi silẹ",
      loadingCommunities: "N fifuye awujọ",
      member: "Ẹgbẹ́",
      members: "Awọn ẹgbẹ́",
      lobbyText:
        "Firanṣẹ ati gba awọn ifiranṣẹ laisi sisopọ foonu rẹ sori ayelujara.",
    },
    settings: {
      pageTitle: "Eto | Lobby",
      sideNavTitle: "Eto",
      searchPlaceholder: "Wa ninu Eto",
      createCommunityText: "Ṣẹda ọkan",
      loadingSettings: "N fifuye eto",
      general: "Gbogbogbo",
      profile: "Profaili",
      chats: "Ifọrọranṣẹ",
      notification: "Ìkìlọ̀",
      personalization: "Atunṣe ti ara ẹni",
      help: "Iranwọ",
      inviteFriends: "Pe awọn ọrẹ",
    },
    settingsGeneral: {
      pageTitle: "Gbogbogbo | Eto",
      title: "Gbogbogbo",
      languageText: "Ede",
    },
    settingsHelp: {
      pageTitle: "Iranwọ | Eto",
      title: "Iranwọ",
      helpCenterText: "Ile Iranwọ",
      helpCenterSubText: "Gba iranwọ, kan si wa",
      termAndPrivacyText: "Awọn ofin ati Ilana Asiri",
      aboutLobbyText: "Nipa Lobby",
    },
    settingsInvite: {
      title: "Pe awọn ọrẹ",
      inviteFriendsText: "Pe awọn ọrẹ",
      inviteFriendsSubText: "Pe ọrẹ rẹ si Lobby, so mọ́ awọn ọrẹ rẹ",
      copyLinkBtn: "Da ọna asopọ Afẹyinti",
      copyLinkAlert: "&#x1F4CB Ọna asopọ ti daakọ si teepu",
    },
    settingsPersonalization: {
      pageTitle: "Atunṣe ti ara ẹni | Eto",
      title: "Atunṣe ti ara ẹni",
      chooseThemeText: "Yan akori rẹ",
      chooseThemeSubText: "Yi akori ti App Lobby pada",
      themeSystem: "Sistemu",
      themeLight: "Imọlẹ",
      themeDark: "Dúdú",
    },
    settingsProfile: {
      pageTitle: "Profaili | Eto",
      title: "Profaili",
      editedProfileText: "Ṣatunkọ profaili",
      signOutText: "Jade",
      bioText: "Igbesi aye",
      noBioText: "O ko ti ṣafikun igbese aye rẹ sibẹ.",
      dobText: "Ọjọ́ ibi",
      dobSubText: "Ọjọ́ ibi rẹ ko han si awọn olumulo miiran",
      noDobText: "O ko ti ṣafikun ọjọ́ ibi rẹ sibẹ.",
    },
    sideNavMobileNavMenu: {
      communitiesText: "Awujọ",
      discoverText: "Awari",
      settingsText: "Eto",
      profileText: "Profaili",
    },
    createCommunityModal: {
      title: "Ṣẹda Awujọ",
      namePlaceholder: "Orukọ",
      descriptionPlaceholder: "Apejuwe",
      createCommunityBtn: "Ṣẹda Awujọ",
      closeBtn: "Pa",
    },
    createRoomModal: {
      title: "Ṣẹda Yara",
      namePlaceholder: "Orukọ",
      descriptionPlaceholder: "Apejuwe",
      enableMessage: "Gba awọn ọmọ ẹgbẹ awujọ laaye lati firanṣẹ awọn ifiranṣẹ",
      createRoomBtn: "Ṣẹda Yara",
      closeBtn: "Pa",
    },
    chats: {
      sendingText: "N firanṣẹ....",
      todayText: "Lónìí",
      yesterdayText: "Àná",
      communityInfoText: "Alaye Awujọ",
      loadingChat: "N fifuye iwiregbe",
      joinCommunityText: "O ko ti darapọ mọ awujọ yii",
      joinCommunityBtnText: "Darapọ mọ lati ri awọn ifiranṣẹ",
      chatInputPlaceHolder: "Kọ ifiranṣẹ rẹ",
      disabledInputPlaceHolder: "O kan alakoso nikan ni o le firanṣẹ ifiranṣẹ",
    },
    notFound: {
      pageTitle: "404 Àkójọkọ Page ko si",
      title: "404 Àkójọkọ Page ko si",
    },
  },
  ha: {
    home: {
      pageTitle: "Al'umma | Lobby",
      sideNavTitle: "Al'ummomi",
      sideNavMenu: {
        create: "Ƙirƙiri Al'umma",
        settings: "Saituna",
      },
      searchPlaceholder: "Bincika al'ummomi",
      openDiscoverText: "Buɗe Gano",
      createCommunityText: "Ƙirƙiri ɗaya",
      addRoomBtn: "Ƙara Daki",
      joinCommunityText: "Ba ka shiga wannan al'ummar ba",
      openDiscoverToJoin: "Buɗe Gano don shiga",
      loadingCommunities: "Ana loda al'ummomi",
      loadingRooms: "Ana loda ɗakuna",
      lobbyText:
        "Aika da karɓi saƙonni ba tare da kunna wayarka ta kan layi ba.",
    },
    discover: {
      pageTitle: "Gano | Lobby",
      sideNavTitle: "Gano",
      sideNavMenu: {
        settings: "Saituna",
      },
      searchPlaceholder: "Bincika al'ummomi",
      open: "Buɗe",
      communityText: "Al'umma",
      joinedCommunity: "Shiga al'umma",
      createCommunityText: "Ƙirƙiri ɗaya",
      openBtn: "Shiga",
      joinBtn: "Shiga",
      leaveBtn: "Bar",
      reportBtn: "Bar",
      loadingCommunities: "Ana loda al'ummomi",
      member: "Mamba",
      members: "Mambobi",
      lobbyText:
        "Aika da karɓi saƙonni ba tare da kunna wayarka ta kan layi ba.",
    },
    settings: {
      pageTitle: "Saituna | Lobby",
      sideNavTitle: "Saituna",
      searchPlaceholder: "Bincika saituna",
      createCommunityText: "Ƙirƙiri ɗaya",
      loadingSettings: "Ana loda saituna",
      general: "Janar",
      profile: "Bayanin martaba",
      chats: "Tattaunawa",
      notification: "Sanarwa",
      personalization: "Keɓancewa",
      help: "Taimako",
      inviteFriends: "Gayyaci abokai",
    },
    settingsGeneral: {
      pageTitle: "Janar | Saituna",
      title: "Janar",
      languageText: "Harshe",
    },
    settingsHelp: {
      pageTitle: "Taimako | Saituna",
      title: "Taimako",
      helpCenterText: "Cibiyar Taimako",
      helpCenterSubText: "Sami taimako, tuntube mu",
      termAndPrivacyText: "Sharuɗɗa da Manufar Sirri",
      aboutLobbyText: "Game da Lobby",
    },
    settingsInvite: {
      title: "Gayyaci abokai",
      inviteFriendsText: "Gayyaci abokai",
      inviteFriendsSubText: "Gayyaci abokinka zuwa Lobby, haɗu da abokanka",
      copyLinkBtn: "Kwafi hanyar gayyata",
      copyLinkAlert: "&#x1F4CB An kwafi hanyar gayyata zuwa allo",
    },
    settingsPersonalization: {
      pageTitle: "Keɓancewa | Saituna",
      title: "Keɓancewa",
      chooseThemeText: "Zaɓi jigo",
      chooseThemeSubText: "Canza jigogin app ɗin Lobby",
      themeSystem: "Tsarin",
      themeLight: "Haske",
      themeDark: "Duhu",
    },
    settingsProfile: {
      pageTitle: "Bayanin martaba | Saituna",
      title: "Bayanin martaba",
      editedProfileText: "Gyara bayanin martaba",
      signOutText: "Fita",
      bioText: "Tarihi",
      noBioText: "Ba ka ƙara tarihin ka ba.",
      dobText: "Ranar haihuwa",
      dobSubText: "Ranar haihuwarka ba a bayyane take ga sauran masu amfani ba",
      noDobText: "Ba ka ƙara ranar haihuwarka ba.",
    },
    sideNavMobileNavMenu: {
      communitiesText: "Al'ummomi",
      discoverText: "Gano",
      settingsText: "Saituna",
      profileText: "Bayanin martaba",
    },
    createCommunityModal: {
      title: "Ƙirƙiri Al'umma",
      namePlaceholder: "Suna",
      descriptionPlaceholder: "Bayanin",
      createCommunityBtn: "Ƙirƙiri Al'umma",
      closeBtn: "Rufe",
    },
    createRoomModal: {
      title: "Ƙirƙiri Daki",
      namePlaceholder: "Suna",
      descriptionPlaceholder: "Bayanin",
      enableMessage: "Ba wa mambobin al'umma damar aika saƙonni",
      createRoomBtn: "Ƙirƙiri Daki",
      closeBtn: "Rufe",
    },
    chats: {
      sendingText: "Aika....",
      todayText: "Yau",
      yesterdayText: "Jiya",
      communityInfoText: "Bayanin al'umma",
      loadingChat: "Ana loda tattaunawa",
      joinCommunityText: "Ba ka shiga wannan al'ummar ba",
      joinCommunityBtnText: "Shiga don ganin saƙonni",
      chatInputPlaceHolder: "Rubuta saƙonka",
      disabledInputPlaceHolder: "Sai admin kawai zai iya aika saƙonni",
    },
    notFound: {
      pageTitle: "404 Shafi ba a samu ba",
      title: "404 Shafi ba a samu ba",
    },
  },
  tr: {
    home: {
      pageTitle: "Topluluk | Lobby",
      sideNavTitle: "Topluluklar",
      sideNavMenu: {
        create: "Topluluk Oluştur",
        settings: "Ayarlar",
      },
      searchPlaceholder: "Toplulukları Ara",
      openDiscoverText: "Keşfet’i Aç",
      createCommunityText: "Bir tane oluştur",
      addRoomBtn: "Oda Ekle",
      joinCommunityText: "Bu topluluğa katılmadınız",
      openDiscoverToJoin: "Katılmak için Keşfet’i Aç",
      loadingCommunities: "Topluluklar Yükleniyor",
      loadingRooms: "Odalar Yükleniyor",
      lobbyText: "Telefonunuzu çevrimiçi tutmadan mesaj gönderin ve alın.",
    },
    discover: {
      pageTitle: "Keşfet | Lobby",
      sideNavTitle: "Keşfet",
      sideNavMenu: {
        settings: "Ayarlar",
      },
      searchPlaceholder: "Toplulukları Ara",
      open: "Aç",
      communityText: "Topluluk",
      joinedCommunity: "Katılınan Topluluk",
      createCommunityText: "Bir tane oluştur",
      openBtn: "Katıl",
      joinBtn: "Katıl",
      leaveBtn: "Ayrıl",
      reportBtn: "Bildir",
      loadingCommunities: "Topluluklar Yükleniyor",
      member: "üye",
      members: "üyeler",
      lobbyText: "Telefonunuzu çevrimiçi tutmadan mesaj gönderin ve alın.",
    },
    settings: {
      pageTitle: "Ayarlar | Lobby",
      sideNavTitle: "Ayarlar",
      searchPlaceholder: "Ayarları Ara",
      createCommunityText: "Bir tane oluştur",
      loadingSettings: "Ayarlar Yükleniyor",
      general: "Genel",
      profile: "Profil",
      chats: "Sohbetler",
      notification: "Bildirimler",
      personalization: "Kişiselleştirme",
      help: "Yardım",
      inviteFriends: "Arkadaşlarını Davet Et",
    },
    settingsGeneral: {
      pageTitle: "Genel | Ayarlar",
      title: "Genel",
      languageText: "Dil",
    },
    settingsHelp: {
      pageTitle: "Yardım | Ayarlar",
      title: "Yardım",
      helpCenterText: "Yardım Merkezi",
      helpCenterSubText: "Yardım alın, bizimle iletişime geçin",
      termAndPrivacyText: "Şartlar ve Gizlilik Politikası",
      aboutLobbyText: "Lobby Hakkında",
    },
    settingsInvite: {
      title: "Arkadaşlarını Davet Et",
      inviteFriendsText: "Arkadaşlarını Davet Et",
      inviteFriendsSubText:
        "Lobby'ye arkadaşını davet et, arkadaşlarınla bağlan",
      copyLinkBtn: "Davet Bağlantısını Kopyala",
      copyLinkAlert: "&#x1F4CB Bağlantı panoya kopyalandı",
    },
    settingsPersonalization: {
      pageTitle: "Kişiselleştirme | Ayarlar",
      title: "Kişiselleştirme",
      chooseThemeText: "Temanızı Seçin",
      chooseThemeSubText: "Lobby Uygulamanızın temasını değiştirin",
      themeSystem: "Sistem",
      themeLight: "Açık",
      themeDark: "Koyu",
    },
    settingsProfile: {
      pageTitle: "Profil | Ayarlar",
      title: "Profil",
      editedProfileText: "Profili Düzenle",
      signOutText: "Çıkış Yap",
      bioText: "Biyografi",
      noBioText: "Henüz biyografi eklemediniz.",
      dobText: "Doğum tarihi",
      dobSubText: "Doğum tarihiniz diğer kullanıcılar tarafından görünmez",
      noDobText: "Henüz doğum tarihinizi eklemediniz.",
    },
    sideNavMobileNavMenu: {
      communitiesText: "Topluluklar",
      discoverText: "Keşfet",
      settingsText: "Ayarlar",
      profileText: "Profil",
    },
    createCommunityModal: {
      title: "Topluluk Oluştur",
      namePlaceholder: "Ad",
      descriptionPlaceholder: "Açıklama",
      createCommunityBtn: "Topluluk Oluştur",
      closeBtn: "Kapat",
    },
    createRoomModal: {
      title: "Oda Oluştur",
      namePlaceholder: "Ad",
      descriptionPlaceholder: "Açıklama",
      enableMessage: "Topluluk üyelerinin mesaj göndermesine izin ver",
      createRoomBtn: "Oda Oluştur",
      closeBtn: "Kapat",
    },
    chats: {
      sendingText: "Gönderiliyor....",
      todayText: "Bugün",
      yesterdayText: "Dün",
      communityInfoText: "Topluluk Bilgisi",
      loadingChat: "Sohbet Yükleniyor",
      joinCommunityText: "Bu topluluğa katılmadınız",
      joinCommunityBtnText: "Mesajları görmek için katılın",
      chatInputPlaceHolder: "Mesajınızı yazın",
      disabledInputPlaceHolder: "Sadece admin mesaj gönderebilir",
    },
    notFound: {
      pageTitle: "404 Sayfa bulunamadı",
      title: "404 Sayfa bulunamadı",
    },
  },
};

export default languages;
